name: render-quarto-markdown

run-name: Running Quarto Render on Markdown Files

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
      - name: Checkout Assignment Repository
        uses: actions/checkout@v4

      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: DSPG-2024/Private-Blog
          token: ${{ secrets.BLOG_PAT_TOKEN }}
          path: DSPG-2024/Private-Blog     

      - name: View Repository Directories
        run: |
          echo "MOVING TO ${{ github.event.repository.name }} Repo"
          ls -a 
          cd DSPG-2024/Private-Blog/
          echo "MOVING TO Private-Blog Repo"
          ls -a
          cd ../../
          echo "MOVING BACK TO ${{ github.event.repository.name }} Repo"
          ls -a
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: "true"

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        
      - name: Install Quarto CLI
        run: |
          wget https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb
          quarto check install
          
      - name: Render QMD File
        env:
          OUTPUT_FILE: "${{ github.actor }}_render_output.html"
        run: |
          R -e "quarto::quarto_render(input = 'Weekly_Team_Blog.qmd', output_format = 'html', output_file = Sys.getenv('OUTPUT_FILE'))"

      - name: Copy Markdown Files and Folders and Push
        if: success()
        env:
          GH_PAT: ${{ secrets.BLOG_PAT_TOKEN }}
        run: |
          echo "ATTEMPTING FILE PUSH"
          cd DSPG-2024/Private-Blog/Assignments/
          rm -rf ${{ github.event.repository.name }} || true 
          mkdir ${{ github.event.repository.name }}
          cd ${{ github.event.repository.name }}
          cp ../../../../Weekly_Team_Blog.qmd .
          cp -r ../../../../Data/ ./Data
          cp -r ../../../../imgs ./imgs
          git add .
          git status 
          git commit -m "Add markdown file output, data folder, and images of ${{ github.actor }}"
          git push https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/DSPG-2024/Private-Blog.git
